### ISSUE TITLE
Errors in exports 

### ISSUE THREAD

**Issue by ynifamily3** [ynifamily3/bigDecimal.js#2]
https://github.com/ynifamily3/bigDecimal.js/blob/7883fee57e59d94cacf31bf16ea2531a64f4f156/enums.js#L19
https://github.com/ynifamily3/bigDecimal.js/blob/7883fee57e59d94cacf31bf16ea2531a64f4f156/util_func.js#L99

**Comment by niceb5y** [comment]
ㄷㄷ
